version: '3'

services:
  server:
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "firstdockerserver"
    
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "firstdockerclient"
    links:
      - "server"
